version: '3.3'
services: 
    ftp:
        image: stilliard/pure-ftpd
        container_name: ftpd_server
        restart: always
        environment:
          PUBLICHOST: localhost
        volumes:
            - C:/Users/Chihhao/Desktop/stable-diffusion-webui-docker:/home/ftpusers/kawsing
        ports:
            - 21:21
            - 30000-30009:30000-30009
        networks:
          - ftp
networks:
  ftp: